# movie_config.yml

dataset: movie
csv_path: /Users/minguhwang/Documents/GitHub/SBU_CS_TeamProject/CSE327/Finalproject/spike_encoded_dataset.csv
img_size: 16
in_channels: 128
time_steps: 10
num_classes: 25
dim: 128

batch_size: 64
val_batch_size: 64
epochs: 1

lr: 0.001
opt: adamw
sched: cosine
weight_decay: 0.05